// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1aSnwTTUB8FBXGnYYwxFJiAwKZkQldDE',
    appId: '1:953247204067:web:f92ad4f28127fbe98bbbd6',
    messagingSenderId: '953247204067',
    projectId: 'mobile-voting-application',
    authDomain: 'mobile-voting-application.firebaseapp.com',
    storageBucket: 'mobile-voting-application.appspot.com',
    measurementId: 'G-BBJDFLQNL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCubbANAuwA6ba-13YUQXss-HH3nEmpHRY',
    appId: '1:953247204067:android:c15851c2effd5aac8bbbd6',
    messagingSenderId: '953247204067',
    projectId: 'mobile-voting-application',
    storageBucket: 'mobile-voting-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVffXPJHwuneykgxFaKfgC4AVAMIXNLlI',
    appId: '1:953247204067:ios:3b68cd9d274568978bbbd6',
    messagingSenderId: '953247204067',
    projectId: 'mobile-voting-application',
    storageBucket: 'mobile-voting-application.appspot.com',
    iosBundleId: 'com.example.mobileVotingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVffXPJHwuneykgxFaKfgC4AVAMIXNLlI',
    appId: '1:953247204067:ios:24116fad8aafeac18bbbd6',
    messagingSenderId: '953247204067',
    projectId: 'mobile-voting-application',
    storageBucket: 'mobile-voting-application.appspot.com',
    iosBundleId: 'com.example.mobileVotingApplication.RunnerTests',
  );
}
